### PR TITLE
Reword connection statistics

### PR DESCRIPTION
**Pull request by pspacek**

### CODE REVIEW

**Comment by pspacek** [comment]
I thought it will be a simple change, but it's not. The trouble is that this sort of connection counting does not work reliably. Sometimes, even with just 1 client socket, one server stop-start cycle adds 20 000 connection attempts or something crazy like that. I'm at loss how this happens.

**Comment by jelu** [comment]
I wouldn't be surprised with those numbers if your IP stack is sending connection refused for all attempts. have you checked with `-vvv` or strace?

**Comment by pspacek** [comment]
Oh sorry, I did not express myself clearly. I've meant 20 000 _successful_ attempts, which does not make any sense. E.g. `Connection attempts:  64040 (22273 successful, 34.78%)`.

**Comment by jelu** [comment]
Can't really replicate this with `dumdumd`. Can you give full instruction how you get this?

**Pull request merged**
