### PR TITLE
binary input format

### PR DESCRIPTION
**Pull request by pspacek**
Add ability to read binary input using TCP stream format (2 bytes packet length, then packet binary, repeat).

New format is used when new option -B is in use. Avoids need to reencode packets repeatedly, and allows to send nonsense packets as well.

### CODE REVIEW

**Comment by pspacek** [comment]
@jelu I think this is ready for review.

**Comment by jelu** [comment]
This is gonna take a while to review. Btw, you've missed `perf_datafile_next()` usage in `resperf.c`.

**Comment by jelu** [comment]
triggering webhooks

**Comment by jelu** [comment]
#build

**Pull request merged**
