### PR TITLE
Update gen-qtype.c.py

### PR DESCRIPTION
**Pull request by gregbo**
Catch URL errors and exit gracefully

### CODE REVIEW

**Comment by jelu** [comment]
This is not really needed and you are only formatting the error, there is no graceful exit because your returning 1.

This script is not mean for users to run.

**Comment by gregbo** [comment]
I thought it would be a good idea to catch the exception and return a succinct error message rather than print out a trace.  The URL might not be accessible at the time the program is run (even if a user is not running it).  For what it's worth, I discussed this with Roy Arends of ICANN, and can forward our correspondence to you, if you wish.

**Comment by jelu** [comment]
I think you've misunderstood what this script does, it's only used to manually re-generate a c file by a developer/maintainer. It is not included or runs by dnsperf/resperf.

**Comment by gregbo** [comment]
I understand what the script does.  I actually (re)familiarized myself with this software and discussed it with Roy Arends before submitting the PR.  When I worked at Nominum about 15 years ago, I worked with dnsperf's ancestor, queryperf.  Anyway, I will keep the repo with the changes available. Anyone who has questions can contact me directly.

**Pull request closed without merging**
